name: Deploy Frontend
on:
    push:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t rbalajee/react-test -f Dockerfile.dev .
            - run: docker run -e CI=true rbalajee/reach-test npm test
